### ISSUE TITLE
Error adding plugin

### ISSUE THREAD

**Issue by hjgamarra** [CesarBalzer/Cordova-Plugin-BTPrinter#15]
Hello, I'm trying to install your plugin

try with
cordova plugin add https://github.com/CesarBalzer/Cordova-Plugin-BTPrinter.git
cordova plugin add https://github.com/CesarBalzer/Cordova-Plugin-BTPrinter/

cordova -v
9.0.0 (cordova-lib@9.0.1)

the error is the same

Failed to fetch plugin https://github.com/CesarBalzer/Cordova-Plugin-BTPrinter/ via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/CesarBalzer/Cordova-Plugin-BTPrinter.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\usuario\AppData\Roaming\npm-cache\_logs\2019-11-17T13_39_40_719Z-debug.log

2019-11-17T13_39_40_719Z-debug.log
--------------------------------------------
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\usuario\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'https://github.com/CesarBalzer/Cordova-Plugin-BTPrinter/',
1 verbose cli   '--production',
1 verbose cli   '--save'
1 verbose cli ]
2 info using npm@6.13.0
3 info using node@v12.13.0
4 verbose npm-session 84a8fe8e6a51aaa4
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for git+https://github.com/CesarBalzer/Cordova-Plugin-BTPrinter.git Error while executing:
7 silly fetchPackageMetaData undefined ls-remote -h -t https://github.com/CesarBalzer/Cordova-Plugin-BTPrinter.git
7 silly fetchPackageMetaData
7 silly fetchPackageMetaData
7 silly fetchPackageMetaData spawn git ENOENT
8 timing stage:rollbackFailedOptional Completed in 3ms
9 timing stage:runTopLevelLifecycles Completed in 1217ms
10 verbose stack Error: spawn git ENOENT
10 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
10 verbose stack     at onErrorNT (internal/child_process.js:456:16)
10 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
11 verbose cwd C:\Users\usuario\cordova\movil
12 verbose Windows_NT 10.0.18362
13 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\usuario\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "https://github.com/CesarBalzer/Cordova-Plugin-BTPrinter/" "--production" "--save"
14 verbose node v12.13.0
15 verbose npm  v6.13.0
16 error code ENOENT
17 error syscall spawn git
18 error path git
19 error errno ENOENT
20 error enoent Error while executing:
20 error enoent undefined ls-remote -h -t https://github.com/CesarBalzer/Cordova-Plugin-BTPrinter.git
20 error enoent
20 error enoent
20 error enoent spawn git ENOENT
21 error enoent This is related to npm not being able to find a file.
22 verbose exit [ 1, true ]

**Comment by bluepharmacy** [comment]
same issue

**Comment by bluepharmacy** [comment]
I tried also `cordova plugin add cordova-plugin-btprinter` but same issue here.. please help us

**Comment by MuhammadOlly** [comment]
First go to code button the source as zip. extract zip and add cordova plugin using local folder

`cordova plugin add C:\Users\<Your User Name>\Downloads\Cordova-Plugin-BTPrinter-master`
`Installing "cordova-plugin-btprinter" for android`
`Adding cordova-plugin-btprinter to package.json`

**Comment by SukhwaniVandana** [comment]
Facing same issue with you plugin link . I am using cordova 11.0.0 . By using local folder as u mentioned @MuhammadOlly above Just one issue I am facing from long is that I have 3 inch thermal printer &  BTPrinter.printBase64() never gives me print for 80mm page.
